rango/urls.py
from django.urls import path,re_path
from rango import views

app_name = "rango"
urlpatterns = [

        path('index/', views.index, name='index_page'),
        path('about/', views.about, name='about_page'),
        re_path('search/$', views.search, name='search_page'),
        re_path('category/(?P<cat_name_slug>[\w\-]+)/$', views.show_category, name='show-category'),
        re_path('page/(?P<page_name_slug>[\w\-]+)/$', views.show_page, name='show-page'),
        re_path('^add_category/$', views.add_category, name='add_category'),
        re_path('^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),

        re_path('^like_category/$', views.like_category, name="like_category"),
        re_path('^suggest/$', views.suggest_category, name="suggest_category"),

        re_path('^register/$', views.register, name='register_page'),
        re_path('^login/$', views.user_login, name='login_page'),
        re_path('^restricted/$', views.restricted, name="restricted_page"),
        re_path('^logout/$', views.user_logout, name="logout_page"),
        
        
    ]

tango/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rango import views


urlpatterns = [
    re_path('^$', views.main, name="main_page"),
    path('admin/', admin.site.urls, name="admin_page"),
    path('rango/', include('rango.urls')),
    re_path('^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0, validators=[MinValueValidator(limit_value=0)])
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)


    class Meta:
    	verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=128)
    views = models.IntegerField(default=0)
    url = models.URLField(max_length=250)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Page, self).save(*args, **kwargs)


    def __str__(self):
        return self.title


class UserProfile(models.Model):
        user = models.OneToOneField(User, on_delete=models.CASCADE)

        website = models.URLField(blank=True)
        picture = models.ImageField(upload_to='profile_images', blank=True)

        def __str__(self):
            return self.user.username




rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=128, 
		help_text="Please enter the CATEGORY NAME.")
	views = forms.IntegerField(initial=0,
		help_text="Category Views")
	likes = forms.IntegerField(initial=0, 
		help_text="Category Likes")
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	class Meta:
		model = Category
		fields = ("name","views","likes",)

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=128, 
		help_text="Enter the TITLE of the page")
	url = forms.URLField(max_length=250,
		help_text="enter the URL of the page")
	views = forms.IntegerField(initial=0, help_text="Page Views")


	class Meta:
		model = Page
		#exclude = ("category",)
		fields = ("title", "url","views",)

	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get("url")

		if url and not url.startswith("http://"):
			url = "http://"+ url
			cleaned_data["url"] = url
			return cleaned_data

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ("username", "email", "password")


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ("website", "picture")

rango/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from rango.models import Category, Page
from rango.forms import CategoryForm,PageForm, UserForm, UserProfileForm
from rango.bing_search import run_query

from datetime import datetime

				
def index(request):
	# request.session.set_test_cookie()
	print(request.scheme)
	print(request.body)
	index_dict = {"index_page":"INDEX", "index_page_status":"active", 
				"category_ordered":Category.objects.order_by("-views")[:7],
				"page_ordered":Page.objects.order_by("-views")[:7]}
	visitor_cookie_handler(request)
	index_dict["visits"] = request.session["visits"]

	response = render(request, "rango/index.html", context=index_dict)

	return response

def about(request):
	# if request.session.test_cookie_worked():
	# 	print("TEST COOKIE WORKED")
	# 	request.session.delete_test_cookie()
	about_dict = {"about_page":"ABOUT", "about_page_status":"active"}
	
	return render(request,"rango/about.html", context=about_dict)

def main(request):
	main_dict = {"main_page_status":"active"}


	return render(request, "rango/main.html", context = main_dict)


def show_category(request, cat_name_slug):
	context_dict = {}
	print(request.method)
	print(request.GET)
	try:
		category_name = Category.objects.get(slug=cat_name_slug)
		category_name.views += 1
		category_name.save()
		pages = Page.objects.filter(category=category_name)
		context_dict['pages'] = pages
		context_dict['category'] = category_name
		
	except Category.DoesNotExist:
		context_dict['pages'] = None
		context_dict['category'] = None

	return render(request, "rango/category.html", context_dict)


def show_page(request, page_name_slug):
	context_dict = {}
	try:
		page = Page.objects.get(slug=page_name_slug)
		page.views += 1
		page.save()
		context_dict["page"] = page

	except Page.DoesNotExist:
		context_dict["page"] = None

	return render(request, "rango/page_detail.html", context_dict)


def add_category(request):
	form = CategoryForm()

	if request.method == "POST":
		form = CategoryForm(request.POST)
		if form.is_valid():
			cat_saved = form.save(commit=True)
			#print(f"Category Name: {cat_saved}, Slug: {cat_saved.slug}")
			return index(request)
		else:
			print(form.errors)
	return render(request, "rango/add_category.html", {"form": form})


def add_page(request, category_name_slug):

	try:
		category = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		category = None

	form = PageForm()
	if request.method == "POST":
		form = PageForm(request.POST)
		if form.is_valid():
			if category:
				page = form.save(commit=False)
				page.category = category
				page.save()
				return show_category(request, category_name_slug)
		else:
			
			print(form.errors)
	return render(request, "rango/add_page.html", {"form": form, "category":category})


def register(request):
	registered = False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			if 'picture' in request.FILES:
				profile.picture = request.FILES["picture"]
			profile.save()

			registered=True
		else:
			print(user_form.errors, profile_form.errors )
			
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'rango/register.html', {'user_form':user_form, 
						'profile_form':profile_form, 'registered':registered})



def user_login(request):
	if request.method == "POST":
		
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('rango:index_page'))
			else:
				return HttpResponse("Your Rango account is DISABLED.")
		else:
			print(f"invalid login details {username}, {password}")
			return HttpResponse("INVALID login details supplied.")
	else:
		return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
	return HttpResponse("Since you're logged in, you can see this text")


def user_logout(request):
	logout(request)

	return HttpResponseRedirect(reverse("rango:index_page"))


def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val


def visitor_cookie_handler(request):
	
	visits = int(get_server_side_cookie(request, "visits", "1"))

	last_visit_cookie = get_server_side_cookie(request, "last_visit", str(datetime.now()))
	last_visit_time	= datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")

	if (datetime.now()-last_visit_time).seconds > 0:
		visits += 1
		request.session["last_visit"] = str(datetime.now())
	else:
		visits = 1
		request.session["last_visit"] = last_visit_cookie
	request.session["visits"] = visits



def search(request):
	content_dict = {"search_page_status":"active"}

	result_list = []
	if request.method == "POST":
		query = request.POST['query'].strip()
		if query:
			result_list = run_query(query)
			result_list = result_list["webPages"]["value"]
			content_dict['result_list'] = result_list
			content_dict['query'] = query
			
	return render(request, 'rango/search.html', context=content_dict)

@login_required
def like_category(request):
	cat_id = None
	if request.method == "GET":
		cat_id = request.GET["category_id"]
	
	likes = 0
	if cat_id:
		cat = Category.objects.get(id=int(cat_id))
		if cat:
			likes = cat.likes + 1 
			cat.likes = likes
			cat.save()
	return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
	cat_list = []
	if starts_with:
		cat_list = Category.objects.filter(name__istartswith=starts_with)

	if max_results>0:
		if len(cat_list) > max_results:
			cat_list = cat_list[:max_results]
	return cat_list


def suggest_category(request):
	cat_list = []
	starts_with	= ""

	if request.method == "GET":
		starts_with = request.GET["suggestion"]
	cat_list = get_category_list(8, starts_with)

	return render(request, 'rango/cats.html', {'cats': cat_list})

templates/rango/about.html


{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    ABOUT PAGE
{% endblock %}

{% block body_block %}
	<h1>{{ about_page }} PAGE</h1>

	<div class="jumbotron">
    {% if user.is_authenticated %}
	    <div>
	            <strong>This is the About Page.</strong><br/><br/>
	    </div>
    
	    <div>
	        <img src="{% static 'images/about.png' %}" alt="Rango about"/>
	    </div>
	{% else %}
		<strong>Outsider. You Cannot See or Edit or Do anyhting on this website. Please Log in.</strong>
	{% endif %}


	</div>
	<button class="btn btn-primary" onclick="alert('You clicked the button using JS.');"> Click me JS</button>

	<button class="btn btn-primary" id="about-btn"> Click me JS on speed</button>
	

	<p>This is example</p><br/>
	<p>This is example 2</p>

	<div id="msg">Hello - I'm here for a Jquery Example too</div>



{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
	ADD CATEGORY
{% endblock %}

{% block body_block %}
	<h1> Add a Category</h1>
		<div class="jumbotron">
			<form id = "category_form" method="post" action="{% url 'rango:add_category' %}"\>
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					<br> {{ field.help_text }} {{ field }} {{ field.errors }} <br>
				{% endfor %}
				<br>
				<button class="btn btn-primary" type="submit" name="Submit">Add the Category</button>
			</form>
		</div>

{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
	ADD PAGE
{% endblock %}

{% block body_block %}
	<div class="jumbotron">
		{% if category %}
		
		<form role="form" id = "page_form" method="post" action="{% url 'rango:add_page' category.slug %}">

		<h2 class="form-signin-heading"> ADD a page to <a href="/rango/category/{{category.slug}}/">{{ category.name }}</a></h2>

			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}

			{% for field in form.visible_fields %}
				
				<br>{{ field.help_text }} {{ field }} {{ field.errors }}<br>
			{% endfor %}
			<br/>
			<button class="btn btn-primary" type="submit" name="Submit"> Add the Page </button>
			</form>

		
		{% else %}
			The specified category DNE
		{% endif %}
	</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>

{% load static %}
{% load rango_template_tags %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="{% static 'js/rango-jquery.js' %}"></script>
<script src="{% static 'js/rango-ajax.js' %}"></script>


<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
	<meta name="description" content="">
	<meta name="author" content="">

	<link rel="icon" href="{% static 'images/favicon.ico'%}">

		<title> Rango - {% block title_block %} 
							How to Tango with Django !
						{% endblock %}
		</title>

		<link rel="stylesheet" href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css">

<!-- 		<link rel="stylesheet" href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"> -->

		<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<!-- 		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"> -->

	</head>
	<body>
		<nav class="navbar navbar-toggleable-xl navbar-inverse fixed-top bg-inverse">
			<a class="navbar-brand" href="{% url 'main_page' %}">Rango</a>

			<div id="navbar">
				<nav class="nav navbar-nav pull-xs-left">
				<a class="nav-item {{ index_page_status }} nav-link" href="{% url 'rango:index_page' %}">Home</a>
				<a class="nav-item {{ about_page_status }} nav-link" href="{% url 'rango:about_page' %}">About</a>
				<a class="nav-item {{ search_page_status }} nav-link" href="{% url 'rango:search_page' %}">Search</a>

				{% if user.is_authenticated %}
				<a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
				<a class="nav-item nav-link" href="{% url 'rango:logout_page' %}?next=/rango/">Logout</a>
				{% else %}
				<a class="nav-item nav-link" href="{% url 'rango:register_page' %}">Register Here</a>
				<a class="nav-item nav-link" href="{% url 'rango:login_page' %}">Log In</a>
				{% endif %}
				<a class="nav navbar-nav nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
			</nav>
		</div>
	</nav>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span3">
				<div class="well sidebar-nav">
					<ul class="nav nav-list">
						<li></li>
						<li></li>
						{% block navbar %}
						{% endblock %}
					</ul>
					{% if user.is_authenticated %}
					<ul class="nav nav-list">
							<li class="nav-header">Find a Category</li>
							<form>
								<li><input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" /></li>
							</form>
					</ul>
					{% endif %}
		    	<div id="cats"></div>
						
				</div>
				
			</div>
<!-- 			<div class="col-sm-3 col-md-2 sidebar">
				{% block sidebar_block %}
					GGGGG
				{% endblock %}
				
			</div> -->
			<hr/>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				{% block body_block %}{% endblock %}
			</div>
		</div>
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
	<script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\
s"></script>


	</body>



</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    <div>
    {% if category %}
        <h1>{{ category.name }} </h1> 
        <div>
        <strong id="like_count">{{ category.likes }}</strong>
        {% if user.is_authenticated %}
            <button class="btn btn-primary btn-sm" id="likes" data-catid="{{ category.id }}" type="button">Like the Category</button>
        {% endif %}
        </div>
        <div> Views : {{ category.views }}</div> <br/>
        {% if pages %}
        <ul>
            {% for pag in pages %} 
            <li><a href="{{ pag.url }}">{{pag.title}}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <strong> No pages currently in category</strong>
        {% endif %}
    {% else %}
        The specified category does not exist !
    {% endif %}
    </div>

    <div>
        <br>
        {% if category %}
        <li><a href="{% url 'rango:add_page' category.slug %}">ADD a PAGE</a></li>
        {% endif %}
    <br/>


{% endblock %}

templates/rango/cats.html
<!-- <ul>
{% if cats %}
	{% for c in cats %}
		<li><a href="{% url 'rango:show-category' c.slug %}">{{ c.name }}</a></li>
	{% endfor %}
{% else %}
	<li> <strong>There are no categories present.</strong></li>
{% endif %}
</ul> -->



{% for c in cats %}
	{% if c == act_cat %}
	<li>
		<strong><a href="{% url 'rango:show-category' c.slug %}">{{ c.name }}</a></strong>
	</li>
	{% else %}
	<li>
		<a href="{% url 'rango:show-category' c.slug %}">{{ c.name }}</a>
	</li>
	{% endif %}
{% endfor %}

templates/rango/index.html

{% extends 'rango/base.html' %}

{% load static %}

{% block title_block %}
    INDEX PAGE
{% endblock %}

{% block body_block %}

    <h1>{{ index_page }} PAGE</h1>
    <div class="jumbotron">
        <h1 class="display-3">Rango says..</h1>        
        {% if user.is_authenticated %}
            <h1>Hey there {{ user.username }}</h1>
            <div class="row marketing">
            <div class="col-lg-6">
                <h4>Most Viewed Categories</h4>
                <p>
                    {% if category_ordered %}
                    <ul class="list-group">
                        {% for category in category_ordered %}
                        <li class="list-group-item"><a href="{% url 'rango:show-category' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <strong>There are no categories present.</strong>
                    {% endif %}    
                </p>
            </div>
            <div class="col-lg-6">
                <h4>Most Viewed Pages</h4>
                <p>
                    {% if page_ordered %}
                    <ul class="list-group">
                        {% for page in page_ordered %}
                        <li class="list-group-item"><a href="{% url 'rango:show-page' page.slug %}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <strong>There are no pages present</strong>
                    {% endif %}
                </p>
            </div>
        </div>
            
            <div>
                <img src="{% static 'images/index.png' %}" alt="Picture of Rango"/>
            </div>

        {% else %}
            <strong>Outsider. You Cannot See or Edit or Do anyhting on this website. Please Log in.</strong>
        {% endif %} 
    </div>


{% endblock %}


templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Login Page
{% endblock %}



{% block body_block %}
<link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
<div class="jumbotron">
	<h1 class="display-3">Login</h1>
</div>



<div class="container">

      <form class="form-signin" role="form" method="post" action="{% url 'rango:login_page' %}">
      	{% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
        
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Sign in</button>
      </form>
</div>



{% endblock %}



<!-- <form id="login_form" method="post" action="{% url 'rango:login_page' %}" >
	{% csrf_token %}
	Username : <input type="text" name="username" value="" size="50">
	<br/>
	Password: <input type="password" name="password" value="" size="50">
	<br/>
	<input type="submit" name="submit" value="LOGIN">

</form> -->

templates/rango/main.html
{% extends 'rango/base.html' %}
{% load static %}


{% block title_block %}
    MAIN PAGE
{% endblock %}

{% block body_block %}

    <h1> MAIN PAGE</h1>
    {% if user.is_authenticated %}
    	<strong>This is the Main Page</strong><br/>  
	    <div>
	<!--         <a href='{% url "admin:index" %}'> Admin Page</a><br/><br/> -->
	        <img src="{% static 'images/main.jpg' %}" alt="Picture of Izmir"/>
	    </div>
	{% else %}
		<strong>Outsider. You Cannot See or Edit or Do anyhting on this website. Please Log in.</strong>

	{% endif %}

{% endblock %}

templates/rango/old_base.html
<!-- 	<div>
		{% block sidebar_block %}
			<h1>SIDEBAR</h1>

			<div>
				{% if user.is_authenticated %}
					Welcome. You are Logged in as : <strong>{{ user.username }}</strong>
					<li><a href="{% url 'rango:logout_page' %}">Log Out</a></li>
					<div>
						<ul>
							{% get_category_list category %}
						</ul>	
					</div>
				{% else %}
					<li><a href="{% url 'rango:login_page' %}">Log In</a></li>
					<li><a href="{% url 'rango:register_page' %}">Sign-Up/Register</a></li>
				{% endif %}

				<br/>
				<li><a href="{% url 'rango:index_page' %}">Index Page</a></li>
				<li><a href="{% url 'rango:about_page' %}">About Page</a></li>
				<li><a href="{% url 'main_page' %}">Main Page</a></li><br/>
				<li><a href="{% url 'admin:index' %}">Admin Page</a></li>
			</div>

		{% endblock %}
	</div>
	<br/>
	<hr>
		

<body>
	<div>
		{% block body_block %}
		{% endblock %}
	</div>

	<br/><br/>
	<hr/>

	<div>
			<ul>
				<li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
				<li><a href="{% url 'rango:about_page' %}">About</a></li>
				<li><a href="{% url 'rango:index_page' %}">Index</a></li>
				<li><a href="{% url 'rango:register_page' %}">Sign Up</a></li>
				<li><a href="{% url 'rango:login_page' %}">Log in</a></li>
			</ul>
	</div> 

</body> -->


<ul>
                <li><a href="{% url 'rango:restricted_page' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add Category</a></li>
            </ul>
            <div>
                <strong>Most Viewed Pages</strong><br/>
                {% if category_ordered %}
                <ul>
                    {% for cat in category_ordered %}
                        <li><a href="{% url 'rango:show-category' cat.slug %}">{{cat.name}}</a></li>
                    {% endfor %}
                </ul>
                {% else %}
                    <strong>There are no categories present</strong><br/><br/>
                {% endif %}
            </div>
            <br/><strong>Most Viewed Pages</strong><br/>
            <div>
                {% if page_ordered %}
                <ul>
                    {% for page in page_ordered %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>    
                {% else %}
                    <strong> There are no Page present</strong><br>
                {% endif %}
            </div>

templates/rango/page_detail.html
{% extends 'rango/base.html' %}

{% block title_block %}
	Page detail
{% endblock %}

{% block body_block %}

	<p>
		Page <strong>{{ page.title }}</strong> belongs to the Category : 
		<a href="{% url 'rango:show-category' page.category.slug %}">{{ page.category.name }}</a>	
	</p>
	
	<p>
		Page url: <a href="{{page.url}}"> {{ page.url }}</a>
	</p>
	<p>
		Page View Count : <strong>{{ page.views }}</strong>
	</p>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Register
{% endblock %}


{% block body_block %}
	<h2 class="form-signin-heading">Sign Up Here </h2>
	
	<h1>Register Page</h1>
	<div class="jumbotron">
	<form role="form" method="post" action=".">
		{% csrf_token %}
		<div class="form-group">
			<p class="required"><label class="required" for="id_username">Username: </label>
				<input class="form-control" id="id_username" max_length="30" type="text" name="username" />
				<span class="helptext">Required. 30 Characters or fewer. Letters, digits and @/./+/-/_ only.</span>

			</p>
			<p class="required"><label class="required" for="id_email">Email:</label>
				<input type="form-control" id="id_email" name="email" type="email" />
			</p>
			<p class="required"><label class="required" for="id_password1">Password:</label>
				<input type="form-control" id="id_password1" name="password1" type="password" />
			</p>
			<p class="required"><label class="required" for="id_password2">Password Confirmation</label>
			<input class="form-control" id="id_password2" type="password" name="password2" />
			<span class="helptext">
				Enter the same password as before, for verification.
			</span>
			</p>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>


{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Search Page
{% endblock %}


{% block body_block %}
	<h1>Search by Rango</h1>
	<div class=jumbotron>
		<form class="form-inline" id="user_form" method="post" action="{% url 'rango:search_page' %}">
			{% csrf_token %}
			<div class="form-group">
				<input class="form-control" type="text" size=50 name="query" id="query" value={{query}} >
			</div>
			<button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
		</form>

	</div>

	<div>
		{% if result_list %}

		<h3>Results</h3>
		{% for result in result_list %}
			<div class="list-group-item">
				<h4 class="list-group-item-heading"><a href="{{ result.url }}" > {{ result.name }} </a></h4>
				<p class="list-group-item-next">{{ result.snippet }}</p>
				
			</div>
		{% endfor %}
		{% endif %}
	</div>


{% endblock %}